# External Firewall (Lille) - Handles external connections and VPN
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "firewall-externe-lille"
  config.vm.network "public_network"  # WAN interface
  config.vm.network "private_network", ip: "192.168.10.1", netmask: "255.255.255.0"  # LAN_DMZ_1
  
  config.vm.provision "shell", path: "firewall_config.sh"
end