Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 6000

  # DHCP Server (Lille)
  config.vm.define "dhcp-lille" do |dhcp_lille|
    dhcp_lille.vm.box = "ubuntu/bionic64"
    dhcp_lille.vm.hostname = "dhcp-lille"
    dhcp_lille.vm.network "private_network", ip: "192.168.20.2", netmask: "255.255.255.0"  # LAN_DHCP
    dhcp_lille.vm.network "private_network", ip: "192.168.50.2", netmask: "255.255.255.0"  # LAN_INT (Lille)
    dhcp_lille.vm.provision "shell", path: "lille_dhcp_config.sh", run: "always"
  end

  # DNS Server (Lille)
  config.vm.define "dns-lille" do |dns_lille|
    dns_lille.vm.box = "ubuntu/bionic64"
    dns_lille.vm.hostname = "dns-lille"
    dns_lille.vm.network "private_network", ip: "192.168.12.2", netmask: "255.255.255.0"  # LAN_DNS
    dns_lille.vm.provision "shell", path: "dns_config.sh", run: "always"
  end

  # External Firewall (Lille)
  config.vm.define "fire-ext-lille" do |fw_externe_lille|
    fw_externe_lille.vm.box = "ubuntu/bionic64"
    fw_externe_lille.vm.hostname = "fire-ext-lille"
    fw_externe_lille.vm.network "public_network"  # WAN interface
    fw_externe_lille.vm.network "private_network", ip: "192.168.10.254", netmask: "255.255.255.0"  # LAN_DMZ_1
    fw_externe_lille.vm.provision "shell", path: "lille_firewall_ext_config.sh", run: "always"
  end

  # Internal Firewall (Lille)
  config.vm.define "fire-int-lille" do |fw_interne_lille|
    fw_interne_lille.vm.box = "ubuntu/bionic64"
    fw_interne_lille.vm.hostname = "fire-int-lille"
    fw_interne_lille.vm.network "private_network", ip: "192.168.11.254", netmask: "255.255.255.0"  # LAN_DMZ_2
    fw_interne_lille.vm.network "private_network", ip: "192.168.12.254", netmask: "255.255.255.0"  # LAN_DNS
    fw_interne_lille.vm.network "private_network", ip: "192.168.13.254", netmask: "255.255.255.0"  # LAN_SMTP
    fw_interne_lille.vm.network "private_network", ip: "192.168.14.254", netmask: "255.255.255.0"  # LAN_NAS
    fw_interne_lille.vm.network "private_network", ip: "192.168.20.254", netmask: "255.255.255.0"  # LAN_DHCP
    fw_interne_lille.vm.network "private_network", ip: "192.168.50.254", netmask: "255.255.255.0"  # LAN_INT (Lille)
    fw_interne_lille.vm.provision "shell", path: "lille_firewall_int_config.sh", run: "always"
  end

  # NAS (Lille)
  config.vm.define "nas-lille" do |nas_lille|
    nas_lille.vm.box = "ubuntu/bionic64"
    nas_lille.vm.hostname = "nas-lille"
    nas_lille.vm.network "private_network", ip: "192.168.14.2", netmask: "255.255.255.0"  # LAN_NAS
    nas_lille.vm.provision "shell", path: "nas_config.sh", run: "always"
  end

  # SMTP Server (Lille)
  config.vm.define "smtp-lille" do |smtp_lille|
    smtp_lille.vm.box = "ubuntu/bionic64"
    smtp_lille.vm.hostname = "smtp-lille"
    smtp_lille.vm.network "private_network", ip: "192.168.13.2", netmask: "255.255.255.0"  # LAN_SMTP
    smtp_lille.vm.provision "shell", path: "smtp_config.sh", run: "always"
  end

  # VPN Server (Lille)
  config.vm.define "vpn-lille" do |vpn_lille|
    vpn_lille.vm.box = "ubuntu/bionic64"
    vpn_lille.vm.hostname = "vpn-lille"
    vpn_lille.vm.network "private_network", ip: "192.168.10.2", netmask: "255.255.255.0"  # LAN_DMZ_1
    vpn_lille.vm.network "private_network", ip: "192.168.11.2", netmask: "255.255.255.0"  # LAN_DMZ_2
    vpn_lille.vm.provision "shell", path: "vpn_config.sh", run: "always"
  end

  # DHCP Server (Rennes)
  config.vm.define "dhcp-rennes" do |dhcp_rennes|
    dhcp_rennes.vm.box = "ubuntu/bionic64"
    dhcp_rennes.vm.hostname = "dhcp-rennes"
    dhcp_rennes.vm.network "private_network", ip: "192.168.21.2", netmask: "255.255.255.0"  # LAN_DHCP (Rennes)
    dhcp_rennes.vm.network "private_network", ip: "192.168.51.2", netmask: "255.255.255.0"  # LAN_INT (Rennes)
    dhcp_rennes.vm.provision "shell", path: "ren_dhcp_config.sh", run: "always"
  end

  # External Firewall (Rennes)
  config.vm.define "fire-ext-rennes" do |fw_externe_rennes|
    fw_externe_rennes.vm.box = "ubuntu/bionic64"
    fw_externe_rennes.vm.hostname = "fire-ext-rennes"
    fw_externe_rennes.vm.network "public_network"  # WAN interface
    fw_externe_rennes.vm.network "private_network", ip: "192.168.21.254", netmask: "255.255.255.0"  # LAN_DHCP (Rennes)
    fw_externe_rennes.vm.network "private_network", ip: "192.168.51.254", netmask: "255.255.255.0"  # LAN_INT (Rennes)
    fw_externe_rennes.vm.provision "shell", path: "ren_firewall_ext_config.sh", run: "always"
  end

end