Vagrant.configure("2") do |config|

    # DHCP Server (Lille)
    config.vm.define "dhcp-server-lille" do |dhcp_lille|
      dhcp_lille.vm.box = "ubuntu/bionic64"
      dhcp_lille.vm.hostname = "dhcp-server-lille"
      dhcp_lille.vm.network "private_network", ip: "192.168.20.2", netmask: "255.255.255.0"  # LAN_DHCP
      dhcp_lille.vm.network "private_network", ip: "192.168.32.2", netmask: "255.255.240.0"  # LAN_INT
      dhcp_lille.vm.provision "shell", path: "lille_dhcp_config.sh"
    end
  
    # DNS Server (Lille)
    config.vm.define "dns-server-lille" do |dns_lille|
      dns_lille.vm.box = "ubuntu/bionic64"
      dns_lille.vm.hostname = "dns-server-lille"
      dns_lille.vm.network "private_network", ip: "192.168.12.2", netmask: "255.255.255.0"  # LAN_DNS
      dns_lille.vm.provision "shell", path: "dns_config.sh"
    end
  
    # External Firewall (Lille)
    config.vm.define "firewall-externe-lille" do |fw_externe_lille|
      fw_externe_lille.vm.box = "ubuntu/bionic64"
      fw_externe_lille.vm.hostname = "firewall-externe-lille"
      fw_externe_lille.vm.network "public_network"  # WAN interface
      fw_externe_lille.vm.network "private_network", ip: "192.168.10.1", netmask: "255.255.255.0"  # LAN_DMZ_1
      fw_externe_lille.vm.provision "shell", path: "lille_firewall_ext_config.sh"
    end
  
    # Internal Firewall (Lille)
    config.vm.define "firewall-interne-lille" do |fw_interne_lille|
      fw_interne_lille.vm.box = "ubuntu/bionic64"
      fw_interne_lille.vm.hostname = "firewall-interne-lille"
      fw_interne_lille.vm.network "private_network", ip: "192.168.11.1", netmask: "255.255.255.0"  # LAN_DMZ_2
      fw_interne_lille.vm.network "private_network", ip: "192.168.12.1", netmask: "255.255.255.0"  # LAN_DNS
      fw_interne_lille.vm.network "private_network", ip: "192.168.13.1", netmask: "255.255.255.0"  # LAN_SMTP
      fw_interne_lille.vm.network "private_network", ip: "192.168.14.1", netmask: "255.255.255.0"  # LAN_NAS
      fw_interne_lille.vm.network "private_network", ip: "192.168.20.1", netmask: "255.255.255.0"  # LAN_DHCP
      fw_interne_lille.vm.network "private_network", ip: "192.168.32.1", netmask: "255.255.240.0"  # LAN_INT
      fw_interne_lille.vm.provision "shell", path: "lille_firewall_int_config.sh"
    end
  
    # NAS (Lille)
    config.vm.define "nas-lille" do |nas_lille|
      nas_lille.vm.box = "ubuntu/bionic64"
      nas_lille.vm.hostname = "nas-lille"
      nas_lille.vm.network "private_network", ip: "192.168.14.2", netmask: "255.255.255.0"  # LAN_NAS
      nas_lille.vm.provision "shell", path: "nas_config.sh"
    end
  
    # SMTP Server (Lille)
    config.vm.define "smtp-server-lille" do |smtp_lille|
      smtp_lille.vm.box = "ubuntu/bionic64"
      smtp_lille.vm.hostname = "smtp-server-lille"
      smtp_lille.vm.network "private_network", ip: "192.168.13.2", netmask: "255.255.255.0"  # LAN_SMTP
      smtp_lille.vm.provision "shell", path: "smtp_config.sh"
    end
  
    # VPN Server (Lille)
    config.vm.define "vpn-server-lille" do |vpn_lille|
      vpn_lille.vm.box = "ubuntu/bionic64"
      vpn_lille.vm.hostname = "vpn-server-lille"
      vpn_lille.vm.network "private_network", ip: "192.168.10.2", netmask: "255.255.255.0"  # LAN_DMZ_1
      vpn_lille.vm.network "private_network", ip: "192.168.11.2", netmask: "255.255.255.0"  # LAN_DMZ_2
      vpn_lille.vm.provision "shell", path: "vpn_config.sh"
    end
  
    # DHCP Server (Rennes)
    config.vm.define "dhcp-server-rennes" do |dhcp_rennes|
      dhcp_rennes.vm.box = "ubuntu/bionic64"
      dhcp_rennes.vm.hostname = "dhcp-server-rennes"
      dhcp_rennes.vm.network "private_network", ip: "192.168.11.2", netmask: "255.255.255.0"  # LAN_DHCP
      dhcp_rennes.vm.network "private_network", ip: "192.168.32.3", netmask: "255.255.240.0"  # LAN_INT
      dhcp_rennes.vm.provision "shell", path: "ren_dhcp_config.sh"
    end
  
    # External Firewall (Rennes)
    config.vm.define "firewall-externe-rennes" do |fw_externe_rennes|
      fw_externe_rennes.vm.box = "ubuntu/bionic64"
      fw_externe_rennes.vm.hostname = "firewall-externe-rennes"
      fw_externe_rennes.vm.network "public_network"  # WAN interface
      fw_externe_rennes.vm.network "private_network", ip: "192.168.10.1", netmask: "255.255.255.0"  # LAN_DMZ
      fw_externe_rennes.vm.provision "shell", path: "ren_firewall_ext_config.sh"
    end
  
end
  