# DNS Server (Lille)
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "dns-server-lille"
  config.vm.network "private_network", ip: "192.168.12.2", netmask: "255.255.255.0"  # LAN_DNS
  
  config.vm.provision "shell", path: "dns_config.sh"
end