# SMTP Server (Lille)
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "smtp-server-lille"
  config.vm.network "private_network", ip: "192.168.13.2", netmask: "255.255.255.0"  # LAN_SMTP
  
  config.vm.provision "shell", path: "smtp_config.sh"
end