# Internal Firewall (Lille) - Protects internal network
Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"
	config.vm.hostname = "firewall-interne-lille"
	config.vm.network "private_network", ip: "192.168.11.1", netmask: "255.255.255.0"  # LAN_DMZ_2
	config.vm.network "private_network", ip: "192.168.12.1", netmask: "255.255.255.0"  # LAN_DNS
	config.vm.network "private_network", ip: "192.168.13.1", netmask: "255.255.255.0"  # LAN_SMTP
	config.vm.network "private_network", ip: "192.168.14.1", netmask: "255.255.255.0"  # LAN_NAS
	config.vm.network "private_network", ip: "192.168.20.1", netmask: "255.255.255.0"  # LAN_DHCP
	config.vm.network "private_network", ip: "192.168.32.1", netmask: "255.255.240.0"  # LAN_INT
	
	config.vm.provision "shell", path: "firewall_config.sh"
  end