# VPN Server (Lille)
Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"
	config.vm.hostname = "vpn-server-lille"
	config.vm.network "private_network", ip: "192.168.10.2", netmask: "255.255.255.0"  # LAN_DMZ_1
	config.vm.network "private_network", ip: "192.168.11.2", netmask: "255.255.255.0"  # LAN_DMZ_2
	
	config.vm.provision "shell", path: "vpn_config.sh"
  end